version: '3'
services:
  milvus:
    image: milvusdb/milvus:latest
    container_name: milvus
    ports:
      - "19530:19530"
      - "19121:19121"
    volumes:
      - ./milvus_data:/var/lib/milvus


volumes:
  milvus_data:
